### ISSUE TITLE
c++ c# interop IDrawingSurfaceManipulationHandler

### ISSUE THREAD

**Issue by martell** [stammen/angleproject#1]
Hey Dale,

Would it be possible for libangle to support
Windows::Phone::Input::Interop::IDrawingSurfaceManipulationHandler

Interop on WP8 would be very nice for WebView login screens and Ads.

Regards
Martell

**Comment by stammen** [comment]
See samples/RotatingCube/RotatingCubeWP8Xaml on the dev branch
