### ISSUE TITLE
glslPrecompiler build failure

### ISSUE THREAD

**Issue by josh-coronalabs** [stammen/angleproject#3]
Attempting to build the "glslPrecompiler" solution causes the following compiler error...
   'rx::Image9' : cannot instantiate abstract class

...in "renderer9.cpp", line 3220.

It happens because the Image class' pure virtual function updateSurface() has an additional boolean argument at the end that the derived Image9 class' function does not have.  That is, the function signatures do not match.

**Comment by stammen** [comment]
I will take a look at it and get back to you. It is probably out of sync with the updated angle code.

**Comment by stammen** [comment]
There is a new compiler program in the dev branch in src/winrtcompiler that is now working for winrt and wp8 shader compilation.
